name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.9'
        architecture: x64
    - run: pip install --constraint=.github/workflows/constraints.txt pip
    - run: pip install --constraint=.github/workflows/constraints.txt nox
    - run: pip install --constraint=.github/workflows/constraints.txt poetry
    - run: nox --sessions tests coverage
    - run: curl -Os https://uploader.codecov.io/latest/linux/codecov
    - run: chmod +x codecov
    - run: ./codecov
